image: gitpod/workspace-full

tasks:
#  - init: sdk install java 17.0.8-amzn;sdk use java 17.0.8-amzn
  - name: install jdk 17
    command: sdk install java 17.0.8-amzn
  - name: use jdk 17
    command: sdk use java 17.0.8-amzn
  - name: build gradle
    command: ./gradlew

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 3306
    onOpen: open-preview
    visibility: public
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 3000
    onOpen: open-preview
    visibility: public
vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab


